---
version: '3'

services:
  ccd-case-management-web:
    environment:
      DM_URL: http://localhost:3453/documents
      DM_URL_REMOTE: http://dm-store:8080/documents
    depends_on:
      - dm-store

  ccd-api-gateway:
    environment:
      PROXY_DOCUMENT_MANAGEMENT: http://dm-store:8080
    depends_on:
      - dm-store

  ccd-data-store-api:
    environment:
      CCD_DM_DOMAIN: http://dm-store:8080

  service-auth-provider-api:
    environment:
      MICROSERVICE_KEYS_EM_GW: "${IDAM_KEY_DM_STORE}"

  dm-store:
    image: "hmcts/dm-store:${DM_STORE_TAG:-latest}"
    command: --wait-for-database 30
    healthcheck:
      disable: true
    environment:
      SERVER_PORT: 8080
      IDAM_SUPERUSER_EMAIL:
      IDAM_SECRET_KEY: "${IDAM_KEY_DM_STORE}"
      GOV_NOTIFY_API_KEY:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ccd-shared-database:5432/evidence
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      #ENABLE_AZURE_STORAGE_CONTAINER: "false"
      #ENABLE_POSTGRES_BLOB_STORAGE: "true"
      STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: "${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-storage-emulator-azurite:10000/devstoreaccount1}"
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME: "${STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:-hmctstestcontainer}"
      BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY_REQUIRED: "${BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY_REQUIRED:-false}"
      BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY: "${BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY:-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDiQ//gc/G53d9dLCtf123fIYo49gUySuJuxOcw2GtieWTMSy+O7RNtsAIjVf3mCOdDNuN69tZNPEWMdaW8n11s9MwYFahtxDecyn0KIP9MvPsfSMSbxhp/f7kfbdB/H/S5eYea66JTyeJS6uNd76RdHttx0mLO30ZkRcXB25c2SIXhRYsdoeKS5GXHDdNejkQM0S/Ev94x2UunApmYHjWN1XcDhsEsAeF4WHnvYh2XiMn9vHY44AqvbWLlAmCgzaXpz8Xhl0fO7jDKSeReDyuM3UTMaiFFaxuvliGol7aIXq/aVe/miiD2SLxHZ6RxAPW80bhXrzJMTLTCqhCEhzfv someone@somewhere.sometime}"
      SPRING_PROFILES_ACTIVE: dev
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      LOGGING_LEVEL_UK_GOV_HMCTS_IDAM: DEBUG
      IDAM_USER_BASE_URI: http://idam-api:8080
      IDAM_S2S_BASE_URI: http://service-auth-provider-api:8080
      S2S_NAMES_WHITELIST: sscs,divorce,ccd,em_gw,document-management-store,ccd_gw,idam-api,fpl_case_service,em_stitching_api,em_ccd_orchestrator
      http_proxy:
      https_proxy:
      no_proxy:
      #      logging env vars
      ROOT_APPENDER: JSON_CONSOLE
      JSON_CONSOLE_PRETTY_PRINT: "false"
      REFORM_SERVICE_TYPE: java
      REFORM_SERVICE_NAME: document-management-store
      REFORM_TEAM: cc
      REFORM_ENVIRONMENT: docker
      #      healthcheck env vars
      PACKAGES_ENVIRONMENT: docker
      PACKAGES_PROJECT: evidence
      PACKAGES_NAME: document-management-store
      PACKAGES_VERSION: unknown
    #      debug mode
    #    JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
      - ccd-shared-database
      - idam-api
      - service-auth-provider-api
    depends_on:
      - ccd-shared-database
      - idam-api
      - service-auth-provider-api
      - azure-storage-emulator-azurite
    ports:
      - 4506:8080
    #   debug port exposed
    #   - 5006:5005

  stitching-api:
    image: hmcts.azurecr.io/hmcts/em-stitching:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stitching-db:5432/emstitch
      - SPRING_DATASOURCE_USERNAME=emstitch
      - SPRING_DATASOURCE_PASSWORD=emstitch
      - S2S_BASE_URI=http://service-auth-provider-api:8080
      - IDAM_API_BASE_URI=http://idam-api:8080
      - ENABLE_LIQUIBASE=true
      - APPINSIGHTS_INSTRUMENTATIONKEY=test-key
      - DM_STORE_APP_URL=http://dm-store:8080
      - DOCMOSIS_ACCESS_KEY=${DOCMOSIS_ACCESS_KEY}
    depends_on:
      - stitching-db
      - dm-store
    links:
      - stitching-db
      - dm-store
    ports:
      - 4630:8080

  stitching-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=emstitch
      - POSTGRES_USER=emstitch
      - POSTGRES_PASSWORD=emstitch

  azure-storage-emulator-azurite:
    image: arafato/azurite
    ports:
      - 10000:10000
    environment:
      executable: "blob"
    volumes:
      - ccd-docker-azure-blob-data:/opt/azurite/folder

volumes:
  ccd-docker-azure-blob-data:
